version: '3.7'

services:
  bottle:
    build: .
    ports:
      - 8081:8081
    environment:
      - MEMCACHED_HOST=memcached
    depends_on:
      - memcached
  memcached:
    image: memcached:1.5.22-alpine
    entrypoint:
      - memcached
      - -m 64
      